### ISSUE TITLE
Automatic class hierarchy would be useful

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#103]
I like using http://www.webgraphviz.com to visualize hierarchies.  I made a graph in `__init__` but it must be updated manually.  It would be nice to have the relevant class hierarchy automatically with a script.  There must be something somewhere that does that.  We could put the code in docs/ or examples/ not sure where. This would be for developers but maybe also users.

```
digraph G {
   rankdir="LR";

    subgraph elements {
        "Matrix" -> "Space"
        "Matrix" -> "Lens"
        "Matrix" -> "Aperture"
        "Matrix" -> "ThickLens"
        "Matrix" -> "CurvedMirror"
        "Matrix" -> DielectricInterface
        "Matrix" -> "MatrixGroup"
        "ThickLens" -> "DielectricSlab"

        "MatrixGroup" -> "AchromaticDoubletLens"
        "AchromaticDoubletLens" -> "thorlabs.part#"
        "AchromaticDoubletLens" -> "eo.part#"
        "MatrixGroup" -> "Objective"
        "Objective" -> "olympus.part#"
    }
}
```

If this can be done in straight Python, perfect.  Avoid using other packages if possible.
I want an output like the one above for webgraphviz.

**Comment by dccote** [comment]
This is a fairly good solution that needs a tiny bit of work:

```python
def allChilds(aClass):
    for child in aClass.__subclasses__():
        print("\"{0}\" -> \"{1}\"".format(aClass.__name__, child.__name__))
        allChilds(child)

if __name__ == "__main__":
    print("digraph G {")
    print("  rankdir=\"LR\";")
    allChilds(Matrix)
    print("}")
```

**Comment by dccote** [comment]
Make sure it gets updated whenever we create new documentation, use other formats if needed, so we can use only Python.  graphviz requires separate, non-python package.

**Comment by PyMarc2** [comment]
Yes. Do you want it to change the .png in the README.md also, or only in the read-the-docs? There's a sphinx extension I found to build the graph, I'll verify if I can output the .png from sphinx also

**Comment by dccote** [comment]
A simple function was added to utils.py for now.
