### ISSUE TITLE
Some imports are not relative

### ISSUE THREAD

**Issue by bopaquin** [DCC-Lab/RayTracing#117]
In the init code, the vendor lenses are imported assuming that the folder raytracing is in the same folder as the code that imports the module. This impedes someone of structuring their project however they want.

**Comment by dccote** [comment]
I fixed the issue by using the proper relative syntax in Pull Request #123

**Comment by bopaquin** [comment]
Actually, the problem is also present in the `__init__.py` file, I was gonna do it earlier but I couldn't push.
