### ISSUE TITLE
rayCountHistogram() and rayAnglesHistogram() of Rays raise exception when already computed

### ISSUE THREAD

**Issue by GabGabG** [DCC-Lab/RayTracing#132]
When we compute `rayCountHistogram()` for a first time, it works perfectly. But when we run it a second time, it throws an exception because a variable is referenced before asignment.

**Comment by GabGabG** [comment]
From what I understand: we cache _yHistogram, but we don't cache the bins, so this is the main problem. But it's not all: if we compute the histogram with, let's say 10 bins, we chache histogram values, then if we want to compute histogram with another number of bins, it won't work because we have cached values. We could keep a parameter about the histogram properties (nb bins, min and max). We should also chache the bin edges, or the xvalues, which are returned at the end and cause the initial issue of the exception.

**Comment by dccote** [comment]
I am not sure anymore that caching the values is that critical, and I hate that it adds a bit of complexity to the process (like the one here!).  That being said, super happy it is 1) noticed 2) solved.
