### ISSUE TITLE
The output of the Matrix.trace is an object in a list

### ISSUE THREAD

**Issue by ElaheParham** [DCC-Lab/RayTracing#148]
According to the function Matrix.trace(), the output should be an object of "Ray" class.

Using a Ray in the input of the function like the following example:

```
from raytracing import *
# M is an ABCD matrix of a lens (f=10)
M= Matrix(A=1,B=0,C=-1/10,D=1,physicalLength=0,label='Lens')
# R1 is a ray
R1=Ray(y=5,theta=20)
Tr=M.trace(R1)
print('the height of traced ray:', Tr.y)
```

I get the following error:
 > AttributeError: 'list' object has no attribute 'y'

Actually the output object is placed in the index 0 of a list. So, if I run the following code and call the "Tr[0].y" It works!

```
from raytracing import *
# M is an ABCD matrix of a lens (f=10)
M= Matrix(A=1,B=0,C=-1/10,D=1,physicalLength=0,label='Lens')
# R1 is a ray
R1=Ray(y=5,theta=20)
Tr=M.trace(R1)
print('the height of traced ray:', Tr[0].y)
```

The output is:
> the height of traced ray: 5.0

-------------------------------------
Since this function is for tracing one ray, It is confusing to have a list at the output.

**Comment by dccote** [comment]
There is a difference between `trace()` and `traceThrough()`: `trace()` will provide a list of rays (a raytrace) at many different point along the path so it can be used it plotting.  The last ray is the output ray. On the other hand, `traceThrough()` will only provide the very last ray, when we do not care about the path in between.  So this is working as expected.

Take a look at `traceThrough()` and how it returns the very last ray only.
