### ISSUE TITLE
Example 4 : Illumination system (Köhler + invariant)

### ISSUE THREAD

**Issue by Valeriouus** [DCC-Lab/RayTracing#152]
Köhler illumination : 
- Show a system with and without the Köhler illumination by showing the conjugate planes of the light source and the sample. If they are overlaid = NOT Köhler, NOT optimal. Why? Because we see the image of the source at the sample, imaging the source at the same time that imaging the sample.

Invariant : 
- Add some invariant definition in that example (how?)

**Comment by shadimasoumi** [comment]
We separated these two examples! (Invariant and Kohler)!
The Kohler text is done, just some modifications to the code are needed! (ray colours)

A new issue has made for Invariant example! and I'll try to write its text based on the new code! (calculation of invariant for each component of the system)
