### ISSUE TITLE
We have `determinant()` and `@property determinant` in different branches

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#158]
Not sure where it happened, but determinant is a function or a property on different branches.
I suggest we change it once and for all to a @property because it appears to fit these guidelines:

https://stackoverflow.com/questions/1374273/when-to-use-properties-instead-of-functions

As it stands, some tests don't run in certain branches.

**Comment by GabGabG** [comment]
I realized it with other methods: There was a commit that removed all `@property` at some point. For example, `hasPower` once was a property but now it is not. I was about to write an issue about that.
