### ISSUE TITLE
List of properties in Matrix.py

### ISSUE THREAD

**Issue by ElaheParham** [DCC-Lab/RayTracing#159]
I recommend the following to be defined as properties in Matrix.py in all branches:
 
```
determinant
hasFiniteApertureDiameter
isImaging
hasPower
```

And maybe `largestDiameter`

**Comment by dccote** [comment]
Let's make sure we can override @property in a subclass, because if we cannot, then that will be a problem, for instance for `largestDiameter` and `hasFiniteApertureDiameter`.

**Comment by GabGabG** [comment]
> Let's make sure we can override @Property in a subclass, because if we cannot, then that will be a problem, for instance for `largestDiameter` and `hasFiniteApertureDiameter`.

Yes, it is possible.
