### ISSUE TITLE
The y-scale is not always set appropriately when the elements have infinite diameters

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#16]
The y-scale is not always set appropriately when the elements have infinite diameters: the rays will go beyond the element drawn on the figure. It should be simple to figure out a way to set the displayHalfHeight appropriately based on the highest ray.

**Comment by dccote** [comment]
This is overlapping with issue #76 and could be fixed at the same time.

**Comment by JLBegin** [comment]
@dccote I think this issue should have been closed with #76 , no ?
