### ISSUE TITLE
Negative value for the entrance pupil diameter (ImagingPath.py)

### ISSUE THREAD

**Issue by ElaheParham** [DCC-Lab/RayTracing#183]
I was working with the ImagingPath.entrancePupil() and I wrote the following example which returns a negative value for both pupil position and pupil diameter.
To me, both negative values do not make sense (Especially a negative value for the entrance pupil diameter!)
Can you please double-check the returned values for this function? 
Maybe it will be solved simply if you use abs before returning the diameter value.

Also to double-check the values I set the path.showEntrancePupil=True and used display() to see the place of the pupil on display but nothing was added to the figure.

```
from raytracing import *
path = ImagingPath() # define an imaging path
path.objectHeight=6
# use append() to add elements to the imaging path
path.append(Space(d=20))
path.append(Lens(f=20,diameter=10,label="f=20"))
path.append(Space(d=30))
path.append(Lens(f=10,diameter=4,label="f=10"))
path.append(Space(d=10))
print('The (position,diameter) of entrance pupil:', path.entrancePupil())
path.showEntrancePupil=True
path.display()
```
> The (position,diameter) of entrance pupil: (-40.0, -8.0)

**Comment by dccote** [comment]
This is correct. I now use the absolute value of the magnification to calculate its size.
