### ISSUE TITLE
ImagingPath.imageSize() includes some prints with out labels

### ISSUE THREAD

**Issue by ElaheParham** [DCC-Lab/RayTracing#184]
The following is the imageSize function:

```
fieldOfView = self.fieldOfView()
(distance, conjugateMatrix) = self.forwardConjugate()
print(distance, conjugateMatrix)
magnification = conjugateMatrix.A
return abs(fieldOfView * magnification)
```
 when I call it it prints as following:
#No (distance)
#matrix (conjugatematrix)
#f=...

I recommend adding some labels before each data that is printed!
Like:
distance from image to object: #No (distance)
conjugate matrix: .............

Because the users probably will not know what does the printed number indicates!

**Comment by dccote** [comment]
In fact, this was removed, it was a forgotten debug statement.  Update from master
