### ISSUE TITLE
Generating unnecessary images 

### ISSUE THREAD

**Issue by Valeriouus** [DCC-Lab/RayTracing#186]
illumination = ImagingPath()

illumination.append(Space(d=10))
illumination.append(Lens(f=10, diameter=100, label="Collector"))
illumination.append(Space(d=10+30))
illumination.append(Lens(f=30, diameter=100, label="Condenser"))
illumination.append(Space(d=30+7))
illumination.append(Lens(f=7, diameter=100, label="Objective"))
illumination.append(Space(d=7+30))
illumination.append(Lens(f=30, diameter=100, label="Tube"))
illumination.append(Space(d=30+10))
illumination.append(Lens(f=10, diameter=100, label="Eyepiece"))
illumination.append(Space(d=10))
illumination.append(Aperture(diameter=20, label="Eye entrance"))
illumination.append(Space(d=10))

illumination.display(limitObjectToFieldOfView=True, onlyChiefAndMarginalRays=True)

Gives this : 

![what](https://user-images.githubusercontent.com/40174887/83067914-71223700-a035-11ea-865e-819e0cc073fc.png)

Because of this : 

![image (1)](https://user-images.githubusercontent.com/40174887/83067938-7aab9f00-a035-11ea-8d95-b2aab1c2b0db.png)

**Comment by dccote** [comment]
This has been fixed. @JLBegin, please indicate which PR # fixed this and close this issue.

**Comment by JLBegin** [comment]
This has not been fix yet. I will push a fix where displayRange ignores height of images if out of display.
