### ISSUE TITLE
ImagingPath: chiefRay returns y=inf and theta=-inf with really big (but not infinite) aperture and no specific y given

### ISSUE THREAD

**Issue by GabGabG** [DCC-Lab/RayTracing#193]
When we create an `ImagingPath` with a really big aperture stop (but not infinite), the chief ray obtained has y = -theta = inf. This doesn't really make sense.

This happens because the aperture is bigger than the max height and at one point (in `fieldOfView`), if `abs(y) < self.maxHeight`, we return `float("+inf")`. If the aperture is bigger than the max height accepted, then we should consider it like an infite aperture?

Example:
```python
path = ImagingPath(System2f(10, 100_000)) # 2f system with f = 10 and 100_000 units aperture
print(path.chiefRay())
```
The output is:
```python
 /       \ 
|    inf  |
|         |
|   -inf  |
 \       /

z = 0.000
```

**Comment by GabGabG** [comment]
If we consider it infinite, then we should be coherent and also consider it infinite everywhere, not only in specific methods, like `fieldOfView` and `fieldStop`. For example, `entrancePupil` and `apertureStop` don't consider the maximum height. Maybe we could override `hasFiniteApertureDiameter` to consider the maximum.

**Comment by dccote** [comment]
I think this particular case is:
1. System2f(10, 100_000) has no aperture stop or field stop
2. chief ray, when no y is provided, uses the edge of the field of view, which in this case is infinite.

In chiefRay, we should check if fieldOfView is defined or infinite before setting y to it:
```
        if y is None and isfinite(self.fieldOfView()):
            y = self.fieldOfView()
        else:
            raise ValueError("Must provide y when field of view is infinite")
```
