### ISSUE TITLE
Error in loading imagingpath.py

### ISSUE THREAD

**Issue by mohamadfeshki** [DCC-Lab/RayTracing#194]
I just pipped the package and it seems there is an invalid syntax Error in imagingpath.py in lines 88,89.
```
thetaUp: float = (stopDiameter / 2.0 - A * y) / B
thetaDown: float = (-stopDiameter / 2.0 - A * y) / B
```
you might need to fix the data type assignment.

**Comment by JLBegin** [comment]
It is valid syntax for Python 3.6+, which fits the raytracing requirements.
