### ISSUE TITLE
MatrixGroup: intermediateConjugates gives duplicates

### ISSUE THREAD

**Issue by GabGabG** [DCC-Lab/RayTracing#205]
When we want the intermediate conjugates of some matrix groups, we have a list with duplicates. Is it normal?

Example:
```python
path = ImagingPath(System4f(10, 5))
print(path.intermediateConjugates())
```
the output is:
```python
[[30.0, -0.5], [30.0, -0.5]]
```
@dccote I feel like it is redundant information.

**Comment by dccote** [comment]
We should remove values that are really close to each other. It happens because it calculates the conjugate plane after each element and they sometimes refer to the same conjugate. We should check for the position and magnification, when they are similar (both), then drop one.
