### ISSUE TITLE
The principal ray does not always align with the images

### ISSUE THREAD

**Issue by JLBegin** [DCC-Lab/RayTracing#216]
When using `onlyChiefAndMarginalRays=True`. The top of the arrow should fit with the chief Ray. It seems to have something to do with conjugates calculations. 

example : 

```
path = ImagingPath()
path.label = "Thick diverging lens"
path.objectHeight = 20
path.append(Space(d=50))
path.append(ThickLens(R1=-20, R2=20, n=1.55, thickness=10, diameter=25, label='Lens'))
path.append(Space(d=50))
path.display(onlyChiefAndMarginalRays=True)
```
![image](https://user-images.githubusercontent.com/29587649/83449411-92ae6480-a421-11ea-8ab1-e781552b1224.png)
![image](https://user-images.githubusercontent.com/29587649/83449441-a22dad80-a421-11ea-8588-40d20212c7cf.png)

**Comment by dccote** [comment]
@JLBegin This code produces images that look weird.
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/14200944/91222070-a8fc5180-e6ec-11ea-9565-a98586203e73.png">

**Comment by JLBegin** [comment]
What is weird? The size of the FoV graphics? Or the spherical interface graphic not fitting with the rays?

**Comment by dccote** [comment]
In fact, now that I think about it, the green line does NOT have to align with the image.  It is the continuity of the other green line that should, and does.
