### ISSUE TITLE
Principal ray should appear as the chief ray passing through the FS with the highest height.

### ISSUE THREAD

**Issue by Valeriouus** [DCC-Lab/RayTracing#251]
def imagingPath(a=10, b=10, title=""):
        path = ImagingPath()
        path.label=title
        path.append(System4f(f1=50, diameter1=a, f2=50, diameter2=b))
        path.append(Aperture(diameter=10, label='Camera'))
        return path

    path = imagingPath(a=15, b=15)
    path.display(limitObjectToFieldOfView=False, onlyChiefAndMarginalRays=True)

![Widefield(a)](https://user-images.githubusercontent.com/40174887/84332758-c42eda80-ab5b-11ea-8ed4-4b6b65f4d295.png)

The green ray should pass just at the edge of the FS, even if it doesn't start at the top edge of the object. Then, it's obvious that not all the object will be properly imaged.

**Comment by dccote** [comment]
As discussed, because you set the object manually, the edge of the object is not the principal ray.   This incoherent option has been removed from display().

**Comment by dccote** [comment]
Reopened after discussion with @Valeriouus : we want to draw the chief ray properly, regardless of what we use for the object.
