### ISSUE TITLE
Default value for deleting temp directory is set to False

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#257]
In `RaytracingTestCase`, the `removeAlreadyExists` is set to false, but I don't see the reason for doing so.  Shouldn't it always remove the temp directory?  If that is the case, then we should remove this check.

**Comment by GabGabG** [comment]
Yes, it is true. I thought maybe someone could change the name of the directory and it could conflict with another existing one. That's why I added this check. But I doubt someone would change this. I will remove the check.
