### ISSUE TITLE
Readthedocs keeps old functions alive 

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#268]
On the page https://raytracing.readthedocs.io/en/latest/modules/raytracing.Lens.html Lens is said to have a `drawAt()` method, but it doesn't: it has been removed.  It is not clear why it still appears in the documentation.

**Comment by JLBegin** [comment]
The stub files of the documentation (all small .rst files in raytracing/docs/modules) are not regenerated by ReadTheDocs... and I have yet to find a way. For now it's still refreshed by hand by deleting the stub files and typing `sphinx-autogen -t docs/_templates docs/reference.rst` in a console. I will do that and push an update.
