### ISSUE TITLE
Matrix with incorrect determinants should not be allowed

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#271]
I am working on getting everything to work properly for focal lengths when the index of refraction is not the same on either side (n1, n2) instead of 1 and 1.  Because when we do that we must make the assumption that the determinant is n1/n2, I added in the branch `differentIndicesOnEitherSides` an exception if the determinant is incorrect (which means the matrix is not physical).  This unfortunately caught many tests that were not really correct, and now (in that branch) we get 42 errors and 6 failures when running all tests. I need help fixing those tests. @GabGabG can you help?

**Comment by GabGabG** [comment]
Yes, I can work on that!
