### ISSUE TITLE
Infinite Space matrix

### ISSUE THREAD

**Issue by GabGabG** [DCC-Lab/RayTracing#274]
With the verification of determinant and n1/n2 (see issue #271), the creation of `Space(d=inf)` fails because `0*inf` is `nan` and `nan` is not 1 (or wathever n1/n2 is). The code then raises the following exception:
`ValueError: The matrix has inconsistent values`. 

@dccote Should we keep it that way or simply raise an exception earlier if we see that `d` is infinite? The message could be more specific for that case. We could also had some code to make sure that `0 * inf` becomes 0 in that case.

**Comment by dccote** [comment]
For Space(), the limit is actually a hard 0, because C=0 precisely and d=infinity would give, in practice, 0. So I changed the calculation of the determinant when C==0 so that B*C is zero in that case.
