### ISSUE TITLE
Materials should take wavelength as a optical parameter

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#276]
We should have a wavelength for a ray, and use it as a parameter when getting the index of refraction of materials. That way, we could fully characterize the chromatic aberrations for a given doublet. If we don't have a wavelength, then use the default design wavelength.

**Comment by dccote** [comment]
@ElodieFlora would like to contribute. Are you planning to do it soon or could she contribute?

**Comment by PyMarc2** [comment]
Oh well I planned working on it this weekend, but I'd prefer if she did it if she wants to get involved! :-) @ElodieFlora

**Comment by dccote** [comment]
Great: you can both work on it, @PyMarc2 you can review her work (then I will complete the merge).

**Comment by PyMarc2** [comment]
Perfect, I'll help!

**Comment by PyMarc2** [comment]
This branch is at the testing step. I'll be showing Elodie and Charels-Eric how to test properly with the unitesting package. Probably towards the begining of next week.
