### ISSUE TITLE
Space matrix sometimes has a negative physical length

### ISSUE THREAD

**Issue by GabGabG** [DCC-Lab/RayTracing#287]
When we compute the backward conjugates (and maybe other methods), we sometimes found a negative distance, which creates a `Space` with a negative distance. I understand that a negative distance means that the space is before the current matrix (for example, if the distance is -10 units, the backward conjugates is 10 units at the left of the current matrix, before the current matrix, in front of, ...), but when we create a `Space` instance the `d` parameter (the negative one in the current issue) is also the pysical length of the matrix. It doesn't make any sense to have a negative *physical* length. I see two possibilities:
- We prevent any `Space` matrix to have a negative `d`. Thus, we could create a *vanilla* matrix `Matrix(1, distance, 0, 1, physicalLength=abs(distance))` instead of a `Space`. We could prevent such illogical `Matrix` creation.
-  We don't prevent `Space` matrices to have a negative `d`, but we take the absolute value of `d` as a physical length. That way, the B component can be negative, but the length cannot.

Example: A `Space` matrix with negative `d` is created in `Matrix`'s `backwardConjugate` when this is executed:
````python
system = System4f(10, 10) * Space(10)
print(s.backwardConjugate())
````
The distance to said backward conjugate is -10, so `Space(-10)` is created which has a physical length of -10.

What should we do?

**Comment by dccote** [comment]
I see the incoherence, but the physicalLength `L` needs to remain negative. This `L` is used to move through the elements and position the next `z` for a ray.  If the move is backwards, then `L` needs to be negative (and backwards). Maybe it is the wrong name for L.  Maybe it should be named `dL`, or `dz`. I think for now we'll need to leave it like that.
