### ISSUE TITLE
Making the font size of axis numbers, legends and labels bigger.

### ISSUE THREAD

**Issue by shadimasoumi** [DCC-Lab/RayTracing#316]

**Comment by JLBegin** [comment]
I agree, but It might depend on the machine. Here is an example of the current display for demo #5.
Can you check that you have a similar display on your end? I also understand that we have to check all display types (ImagingPath, GaussianBeam, Intensity profiles)

```python
path = ImagingPath()
path.label = "Demo #5: Simple microscope system"
path.append(Space(d=4))
path.append(Lens(f=4, diameter=0.8, label='Obj'))
path.append(Space(d=4 + 18))
path.append(Lens(f=18, diameter=5.0, label='Tube Lens'))
path.append(Space(d=18))
path.display()
```
![demo5](https://user-images.githubusercontent.com/29587649/87446335-29487680-c5c7-11ea-8ad9-b2aa4ea775df.png)

**Comment by shadimasoumi** [comment]
This is mine!

![image](https://user-images.githubusercontent.com/59581437/87448351-b8568e00-c5c9-11ea-99db-4c209c5c0712.png)
