### ISSUE TITLE
Axicon does not work anymore because it cannot multiply matrices

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#332]
Any example with Axicons don't work anymore: the new `Figure.py` makes use of `transferMatrix()`, which cannot be calculated with an axicon.

**Comment by dccote** [comment]
@JLBegin I would like to see this fixed.  Do you have time?

**Comment by JLBegin** [comment]
Yes i can look into that. Looks like the axicon cannot be used in an imaging path
