### ISSUE TITLE
FOV and Image size should be a hollow blue arrow and hollow red arrow to mirror the object and image.

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#353]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/14200944/91252476-ab31d080-e72b-11ea-8533-1f2c0f9dc235.png">

**Comment by JLBegin** [comment]
ok but this might conflict with the Object color which can be set when using multiple objects (setting object color results in an image with the same color but hollowed : 
ObjectRays(color='g')
![image](https://user-images.githubusercontent.com/29587649/91306728-f3c4aa80-e77a-11ea-88e3-a5022a1d2c94.png)

We could set FOV as blue and red hollow eitherway and the user would just preferably choose another color if he wants to use 
multiple objects
