### ISSUE TITLE
onlyChiefAndMarginalRays renamed to onlyPrincipalAndAxialRays?

### ISSUE THREAD

**Issue by calocedrus** [DCC-Lab/RayTracing#355]
I'm running the `demo.py` and it stops at the Thick diverging lens example complaining that the keyword `onlyChiefAndMarginalRays` is unexpected in the call to `path.display(onlyChiefAndMarginalRays=True)`.
Tracing back in the old code I had (raytracing 1.1.9) and the current (latest, from master branch) I see that there is no more `onlyChiefAndMarginalRays` in `raytracing/imagingpath.py` , it seems it's been renamed to `onlyPrincipalAndAxialRays`, is that correct?
Ludo

**Comment by dccote** [comment]
Yes it is.  We will fix the files, I believe we had forgotten the `demo.py` file.

**Comment by dccote** [comment]
Done.  It is in the `1.3.1-bugFixes` branch and will be merged once the article is out and other bugs have been found and fixed.
