### ISSUE TITLE
The axicon does not work properly

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#370]
The code now makes use of transferMatrix in the figure API.  However, the axicon class does not play well because it modifies the multiplication rules.  This means we cannot use the axicon class anymore, but we could before.

**Comment by xkronosua** [comment]
In function `deviationAngle` you should change sign and add `abs` in order to handle flipped axicon.
Instead of:
```
(self.n - 1.0) * self.alpha
```
it should be:
```
-(self.n - 1.0) * abs(self.alpha)
```
