### ISSUE TITLE
When running remotely without a display, matplotlib fails and blocks the code

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#412]
Running remotely is a problem is there is no backend for matplotlib.  It fails and blocks the code.
We need to figure this out and set the backend to 'Agg' or something like that.

Any code using `display()` will essentially freeze.

This is rare: it is only when running on remote servers.

**Comment by JLBegin** [comment]
Hard to detect because the backend itself is still available and working when accessing from remote. plt.show() runs but it cannot display anything from the remote command line. We would need to detect remote usage (could not find how to do that) and switch to Agg.
