### ISSUE TITLE
Fiber optic // numerical aperture

### ISSUE THREAD

**Issue by Antoniin** [DCC-Lab/RayTracing#426]
Bonjour,

J’ai fait un parcourt optique ou la lumière était focussé dans un fibre optique. Puisque la fibre avait un NA, j’ai forcé un angle d’entré de celle-ci avec un aperture stop. Il est cependant à noté que l’aperture stop ne fonctionnait pas pour tout les rayons. Je me demandais si un ajout à ce niveau est planifié?

Merci

Antonin
//
Hello,

I did an opticalpath where the light was focused into an optical fiber. Since the fiber had an NA, I forced an entry angle of it with an aperture stop. It should be noted, however, that the aperture stop did not work for all rays. I was wondering if an addition to this level is planned?

Thank you

Antonin

**Comment by dccote** [comment]
Done in 1.3.7
