### ISSUE TITLE
Version check slows down module import in offline environments

### ISSUE THREAD

**Issue by himbeles** [DCC-Lab/RayTracing#433]
Thank you for making this nice raytracing library available.
In our corporate environment, we can not rely on a permanent internet connection. 
Consequently, we are getting wait times of several seconds on every import of `raytracing` with failing automated module version check.

Would it be an option for you to remove this automated check? 
Anyhow I think, it is good practice to leave the version control to the package manager and end user. 

Thank you again.

**Comment by himbeles** [comment]
PR #434 would remove the automated version check.

**Comment by dccote** [comment]
Sorry for the delay.  I really want the automatic version check, I will find a better way of doing it and failing quickly if no internet is available.

**Comment by himbeles** [comment]
Sure, thanks for the feedback.
