### ISSUE TITLE
Display of DielectricInterfaces is incorrect

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#436]
In the folder `raytracing/specifications`, there is a file called `lensBuilder.py` to build a lens from a prescription.  In the case of objectives, with many interfaces, the display is particularly incorrect, as the interfaces continue and cross the previous interfaces.  We need to:

1. Stop the drawing when the cross previous interfaces
2. In fact, draw combinations Interface+Space(n!=1)+Interface as a single polygon with a tint that indicates the index of refraction. 

I photoshopped what it should look like below (same blue however)

<img width="1001" alt="image (7)" src="https://user-images.githubusercontent.com/14200944/164473040-8f6050b5-bbee-45b8-a6c8-79a2787bd1c1.png">
<img width="828" alt="image (8)" src="https://user-images.githubusercontent.com/14200944/164473052-b93260ab-5a11-4f0e-a44c-c1bea463a363.png">

**Comment by JLBegin** [comment]
Using the CompoundLens class and adding a default `forwardSurfaces` property currently leads to the following display: 
![snap_lensBuilder](https://user-images.githubusercontent.com/29587649/165649630-ef42c37f-06f6-4a4d-9b0b-3da6d2830388.png)

It is currently not cropped to the desired lens diameter so I will look into that.

**Comment by JLBegin** [comment]
Added diameter argument to CompoundLens in order to correctly set apertureDiameter (default to infinity). 
@dccote is this the figure you were expecting ?
![snap_lensBuilder_dia](https://user-images.githubusercontent.com/29587649/165658756-6f158623-a970-4dcb-bc95-2bf0ac67e538.png)
