### ISSUE TITLE
'ImagingPath' object has no attribute 'traceManyTrough'

### ISSUE THREAD

**Issue by Carol1117** [DCC-Lab/RayTracing#441]
can not find the function 'traceMany Through' in class ImagingPath

**Comment by PyMarc2** [comment]
@Carol1117 
To help us debug faster, please provide the following information:

- Your OS and version
- Your python version
- Your PyTissueOptics module version
- The full code you are trying to run.

**Comment by dccote** [comment]
The following code does work:

```
from raytracing import *

path = ImagingPath()
path.append(Space(d=70))
path.append(Lens(f=35, diameter=25))
path.append(Space(d=70))

inputRays = RandomUniformRays()
outputRays = path.traceManyThrough(inputRays)

inputRays.display()
outputRays.display()
```

[intput.pdf](https://github.com/DCC-Lab/RayTracing/files/8826250/intput.pdf)
[output.pdf](https://github.com/DCC-Lab/RayTracing/files/8826251/output.pdf)
