### ISSUE TITLE
Mirrors?

### ISSUE THREAD

**Issue by toddkarin** [DCC-Lab/RayTracing#454]
Is it possible to model a curved mirror? Thanks kindly!

**Comment by dccote** [comment]
Yes it is very easy. I will add it, but in fact, in terms of math, a lens with the same focal length will do exactly the same.

**Comment by dccote** [comment]
You could also just temporarily add this to your code, with R negative for a converging mirror:
 ```
class CurvedMirror(Matrix):
    def __init__(self, R):
        self.R = R
        Matrix.__init__(self, A=1, B=0, C=2/R, D=1)
```

**Comment by dccote** [comment]
Included in main code. Will be relased soon.
