### ISSUE TITLE
UnboundLocalError: local variable 'fanAngle' referenced before assignment

### ISSUE THREAD

**Issue by jacomore** [DCC-Lab/RayTracing#460]
Dear all, 
Thanks for the extremely simply but yet powerful software. 
I encountered a bag in the version 1.3.9. 
The error is: “**UnboundLocalError: local variable 'fanAngle' referenced before assignment**”.
It occurs when the user sets a fanAngle attribute in  imagingPath instance and then displays it. Here's an example:

path = ImagingPath() # define an imaging path
#set the desire properties
path.fanAngle=0.1
path.objectHeight=1.5
path.fanNumber=5
path.append(Space(d=20))
path.append(Lens(f=10)
path.append(Space(d=10))
path.display()

The is error occurs because at the line 997 of the imagingpath.py file the **“self”** before fanAngle is missing. 
Therefore, there are two references to the same attribute fanAngle, thus causing an error. In particular:
 

**996**  defaultObject = ObjectRays(self.objectHeight, z=self.objectPosition,
**997**                                       _halfAngle=fanAngle_, T=self.rayNumber, H=self.fanNumber)

Just add a "self" in front of it and it’s solved. 
Best wishes

**Comment by dccote** [comment]
Seems to be fixed.
