### ISSUE TITLE
drawWaist gone ?

### ISSUE THREAD

**Issue by ThisIsUserNa** [DCC-Lab/RayTracing#472]
Hello,
I'm trying to use your library and specifically the "drawWaist" method but it seems that it's gone ? 

Have a nice day !

**Comment by dccote** [comment]
That is odd.  Can you give me the code you were using?

**Comment by ThisIsUserNa** [comment]
Hi,
I don't have the code right now but it was something like path = LaserPath() / Append stuff / path.display(beams=Gaussianbeam...)/ and path.drawWaist

But if you look at the code of your library version 1.2.9 the method "drawWaist" exist in the laserpath class, but in the last version 1.3.X the method is not there anymore. That's why I find it weird, as if you removed it ? 

Thank for your answer :)
