### ISSUE TITLE
Object and Image arrows often look weird when object/image very small

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#48]
We need an intelligent way of showing very small objects.

**Comment by JLBegin** [comment]
- The size of the arrow heads (and aperture ticks) should scale with the display's FOV and the arrow's relative length.
- A constant blank space (relative to the FOV) should also be left in the Y-axis of the display.
- The default fan angle could also scale with the display.
- Are the object labels too small ?
- When an object is too small to be noticed, we could add an additional label or something else (need more thinking).
- Do we want all the traced rays to be present inside the display (y-scale)? or just the objects?
