### ISSUE TITLE
Evaluate various documentation formats, make a choice

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#49]
The documentation is currently based on simple docstrings.  We need better by looking at Sphynx and other options. Ideally, the format will automatically produce a nice looking HTML or Markdown output.

@elahe: Looking at documentation requirements:
1) what information do we need to provide to users? (function description, examples, tutorials, etc...)
2) what is the best format to provide this information? (web site, online help, etc...)
3) what are possible methods to do 1) and 2) ?

It may be interesting to look at https://readthedocs.org

**Comment by JLBegin** [comment]
Similar to scikit-learn, I think we should have a typical API reference documentation (auto-generated from doctrings) and a user guide (including various demos). 

Regarding the API reference, the doctrings should follow a standard format like [Numpy](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy) and include a description, the inputs, the outputs and some examples. 

The HTML is easily generated by [Sphinx](https://www.sphinx-doc.org/en/master/) using reStructuredText code.

**Comment by JLBegin** [comment]
I think this issue should be merged with #30

**Comment by PyMarc2** [comment]
+1 for the use of Sphinx from reStrcutu. I think it is the conventionnal and most robust way to produce documentation in python since the guidelines are clear in the doc. I don't think it should be a difficult choice.
