### ISSUE TITLE
Better coverage for Unit testing needed

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#52]
Best places to start: `Matrix`, then `MatrixGroup`, `OpticalPath`, then `ImagingPath`

Read the procedure for writing tests on https://github.com/DCC-Lab/RayTracing/wiki/HOWTO-write-Unit-Tests.

Unit tests are very limited at this point.  To create more tests, do to the tests directory and create a file with a name starting with `testsWhatever.py`. Look at other files for examples.
To run, simply use: `python -m unittest testsWhatever.py`.
To run with coverage, use: `coverage run -m unittest discover`, then `coverage html` and look at `coverage_html_report/index.html`.

**Comment by GabGabG** [comment]
@dccote Is there a reason why there are 3 different files to test matrix? matrixTests.py, testMatrix.py and testsMatrix.py

**Comment by JLBegin** [comment]
@GabGabG just to let you know that I'm currently debugging and testing `MatrixGroup.largestDiameter()`, `ImagingPath.displayRange` (new) and `Matrix.AxesToDataScaling()` in another branch called `display`.

**Comment by dccote** [comment]
Replaced by smaller issues specific to files.
