### ISSUE TITLE
Create a HOWTO describing how to write unit tests, put it on Wiki

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#54]
We need someone to write a procedure for writing tests and put it on the Wiki
at https://github.com/DCC-Lab/RayTracing/wiki/HOWTO-write-Unit-Tests

**Comment by MFournierQC** [comment]
I added what I wrote to the wiki. It will need reviewing.

It is very "Teaching and Learning" oriented.

**Comment by dccote** [comment]
Good start but some details need to be moved to the end.  We will look at it again later. ok for now.
