### ISSUE TITLE
Cardinal points for ThickLens are not shown

### ISSUE THREAD

**Issue by FrancoisCoteIng** [DCC-Lab/RayTracing#64]

**Comment by JLBegin** [comment]
Are you only referring to the focal points or all cardinal points? I think the code is set to only display the focal points.

**Comment by JLBegin** [comment]
I noticed that while the focal points labels get displayed, the focal point marker doesn't in fact. The call is missing. This is fixed by adding `self.drawCardinalPoints(z=z, axes=axes)` at the end of `ThickLens.drawAt()`.
