### ISSUE TITLE
Example: confocal detection through pinhole 

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#75]
We will show the code (or small excerpts) for various problems.  I need code for:

Intensity through confocal detection through pinhole for different pinholes, like the problem set in BPH-Imaging class.

**Comment by dccote** [comment]
Good, but two things:
1. Change the name of the file to confocalDetection.py
2.  Include the "text" in the `article.md` file.

**Comment by Valeriouus** [comment]
@ElaheParham @JLBegin (if you are not overwhelmed by my questions hihihi) @dccote review the new code using now magnification ! 
Branch : fixExamplesDirectory
Code : confocaldetection.py

**Comment by dccote** [comment]
Merged.
