### ISSUE TITLE
ImagePath should default to principal and axial ray if they exist

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#78]
Currently, the default when displaying a trace is to use a user-defined objectHeight and fanAngle with decent default values.  This is probably not that useful.  We should default to principal and axial rays when they exist and use a unity object height otherwise. Probably.

**Comment by dccote** [comment]
@JLBegin Confirm this is done.

**Comment by JLBegin** [comment]
Yes, changed with #246
