### ISSUE TITLE
Dependencies must be more explicit

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#81]
Because we mostly use Anaconda, we are not explicitly stating the dependencies in `setup.py`. We need to go through the list of dependent modules if one does not use anaconda.

**Comment by PyMarc2** [comment]
I went through it methodically.
the only dependencies which are not python standard library based are env, matplotlib and numpy. wow!

**Comment by dccote** [comment]
As mentionned, env is an internal package, so I renamed it envtest.py
