### ISSUE TITLE
display() and save() should use essentially the same code

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#82]
Currently, they are almost the same but options may be missing.

**Comment by JLBegin** [comment]
We could wrap their content in something called createFigure ? or you want to merge display and save functions together and add an option like `save: bool=False` ?

**Comment by JLBegin** [comment]
@dccote can you review this [commit](https://github.com/DCC-Lab/RayTracing/pull/76/commits/bca2f954659765ead61b985c6c4a0667d65590d8) ?

**Comment by dccote** [comment]
Completed in PR Improved Display.
