### ISSUE TITLE
CurvedMirror and ThickLens don't override flipOrientation

### ISSUE THREAD

**Issue by GabGabG** [DCC-Lab/RayTracing#86]
CurvedMirror and ThickLens do not override flipOrientation. This is a problem, because in the case of:

1. CurvedMirror:
 - R should become -R. This changes the C component of the ABCD matrix.
2. ThickLens:
 - R1 sould become -R2 (and vice versa). This changes the A and D components.

**Comment by dccote** [comment]
You are right.

**Comment by dccote** [comment]
I think ThickLens() flipping is more then A <-> D because R1 and R2 change sign.
