### ISSUE TITLE
ImagingPath and LaserPath methods in MatrixGroup raise exception.

### ISSUE THREAD

**Issue by GabGabG** [DCC-Lab/RayTracing#90]
They respectively return a ImagingPath instance and a LaserPath instance, but those classes are in other files not imported. It is also worth mentioning that they both inherit from MatrixGroup, so it is kind of incoherent to use them in MatrixGroup.

Question:
Are those methods really necessary in MatrixGroup?
- Yes: We have to find a way to import them without having a circular import problem.
- No: We should remove them.

**Comment by dccote** [comment]
HUmmm..... Hard one: they are convenient if you work with MatrixGroup and then decide to look at at as an imagingPath or LaserPath().  But you are right, it does not belong in the parent class. 
We should instead have a conversation niece init in `ImagingPath` and `LaserPath` that can take a `MatrixGroup`
